import 'styles/globals.css'

export const metadata = {
  title: 'BTN - Next App Router',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="container mx-auto pt-4">{children}</body>
    </html>
  )
}
