import Observability from '../components/Observability'

import 'styles/globals.css'

export const metadata = {
  title: 'Tennis BTN - Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="container mx-auto pt-0 max-w-lg">{children}</body>
      <Observability />
    </html>
  )
}
