import MobileFooter from 'app/ui/MobileFooter'
import MobileHeader from 'app/ui/MobileHeader'
import 'styles/globals.css'

export const metadata = {
  title: 'Tennis BTN - Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="container mx-auto pt-0 max-w-lg">
        {/* <MobileHeader /> */}
        {children}
        <MobileFooter />
      </body>
    </html>
  )
}
